# docker-compose.yml
version: '3'

services:
  app:
    build:
      context: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/budgetwise
    depends_on:
      - db


  db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=budgetwise
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: