# docker-compose.yml

services:
  app:
    build:
      context: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/budgetwise
    depends_on:
      - db


  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: budgetwise
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: