services:
  app:
    build:
      context: .
    environment:
      - DATABASE_URL=postgresql://postgres:pass@db:5432/budgetwise
    depends_on:
      - db
    volumes:
      - ./budgetwise_cli/infra/migrations:/app/budgetwise_cli/infra/migrations

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: budgetwise
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: