# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"  # Install from setup.py with dev extras
      - name: Lint with Black
        run: black --check --exclude "budgetwise_cli/infra/migrations/" .
      - name: Lint with Ruff
        run: ruff check .
      - name: Type check with MyPy
        run: mypy budgetwise_cli 

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_budgetwise
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_budgetwise
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"  # Install from setup.py with dev extras
      - name: Run tests
        run: pytest

  docker:
    runs-on: ubuntu-latest
    needs: [lint, test]  
    steps:
      - uses: actions/checkout@v3
      
      - name: Build with Docker Compose
        run: docker compose build
      
      - name: Test Docker image
        run: docker compose run --rm app python -m budgetwise_cli.cli.app --help
          
      
     
